require('settings')
require('mappings')
require('autocommands')

if vim.g.vscode == nil then
    vim.cmd('packadd nvim-web-devicons')
    vim.cmd('packadd ale')
    vim.cmd('packadd barbar.nvim')
    vim.cmd('packadd chadtree')
    vim.cmd('packadd coc.nvim')
    vim.cmd('packadd csv.vim')
    vim.cmd('packadd feline.nvim')
    vim.cmd('packadd lualine.nvim')
    vim.cmd('packadd plenary.nvim')
    vim.cmd('packadd QFEnter')
    vim.cmd('packadd tagbar')
    vim.cmd('packadd telescope.nvim')
    vim.cmd('packadd tmuxline.vim')
    vim.cmd('packadd vim-compiler-pytest')
    vim.cmd('packadd vim-dispatch')
    vim.cmd('packadd vim-fugitive')
    vim.cmd('packadd vim-grepper')
    vim.cmd('packadd vim-python-pep8-indent')
    vim.cmd('packadd vimspector')
    vim.cmd('packadd vim-test')
    vim.cmd('packadd vim-vinegar')
    vim.cmd('packadd vim-virtualenv')
    require('plugin_ale')
    require('plugin_barbar')
    require('plugin_coc')
    require('plugin_grepper')
    require('plugin_lualine')
    require('plugin_nightfox')
    require('plugin_supertab')
    require('plugin_telescope')
    require('plugin_test')
    require('plugin_vimspector')
end
